development:
  adapter: postgresql
  encoding: unicode
  database: domdcu1kmqc2m
  pool: 5
  username: tsueatkihvzpvz
  password: mRm8U0HgOhNen6GDdgGemBQXIT

test:
  adapter: postgresql
  encoding: unicode
  database: domdcu1kmqc2m
  pool: 5
  username: tsueatkihvzpvz
  password: mRm8U0HgOhNen6GDdgGemBQXIT

production:
  adapter: postgresql
  encoding: unicode
  database: domdcu1kmqc2m
  pool: 5
  username: tsueatkihvzpvz
  password: mRm8U0HgOhNen6GDdgGemBQXIT